apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myd
  name: myd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myd
    spec:
      containers:
      - image: vimal13/lwweb:v2
        name: apache-webserver-php
        resources: {}
status: {}
