apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myd
    app.kubernetes.io/instance: mylwapp
  name: myd
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: myd
  type: LoadBalancer
status:
  loadBalancer: {}
